name: EditorConfig Lint

on:
  push:
    branches: [ main, main-beta, dev ]
  pull_request:
    branches: [ main, main-beta, dev ]
  workflow_dispatch:

env:
  node-version: 14.x

jobs:
  editorconfig:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node v${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}
      - name: Install NPM Dependencies
        run: npm ci
      - name: Run EditorConfig Check
        run: npm run lint:editorcfg
