#-----------------------------
# CI Github Action: Release
#-----------------------------

name: release

on:
  workflow_dispatch:

env:
  node-version: 12.x

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node v${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - name: Install NPM Dependencies
        run: npm ci

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GIT_AUTHOR_NAME: ala-n
          GIT_AUTHOR_EMAIL: astsefanovich@exadel.com
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
